spring.cloud.stream:
  function:
    definition: processAccount
  bindings:
    processAccount-in-0:
      destination: user-registration
    processAccount-out-0:
      destination: account-activation

  kafka:
    bindings:
      processAccount-in-0:
        consumer:
          configuration:
            key:
              serializer: org.apache.kafka.common.serialization.LongSerializer

      processAccount-out-0:
        producer:
          configuration:
            key:
              serializer: org.apache.kafka.common.serialization.LongSerializer

    streams:
      binder:
        brokers:
          - ec2-3-7-157-60.ap-south-1.compute.amazonaws.com:9092